export const _categories = {
    bienestar: {
        order: 6,
        name: 'Bienestar',
        slug: 'bienestar',
        markerUrl: '/bienestar-marker.svg',
        iconUrl: '/bienestar-icon.svg',
        color: '#00C7BE',
    },
    cultura: {
        order: 2,
        name: 'Cultura',
        slug: 'cultura',
        markerUrl: '/cultura-marker.svg',
        iconUrl: '/cultura-icon.svg',
        color: '#5856D6',
    },
    educacion: {
        order: 7,
        name: 'Educación',
        slug: 'educacion',
        markerUrl: '/educacion-marker.svg',
        iconUrl: '/educacion-icon.svg',
        color: '#8E4B21',
    },
    entretencion: {
        order: 1,
        name: 'Entretencion',
        slug: 'entretencion',
        markerUrl: '/entretencion-marker.svg',
        iconUrl: '/entretencion-icon.svg',
        color: '#FF2D55',
    },
    deporte: {
        order: 5,
        name: 'Deporte',
        slug: 'deporte',
        markerUrl: '/deporte-marker.svg',
        iconUrl: '/deporte-icon.svg',
        color: '#FF3B30',
    },
    familiar: {
        order: 4,
        name: 'Familiar',
        slug: 'familiar',
        markerUrl: '/familiar-marker.svg',
        iconUrl: '/familiar-icon.svg',
        color: '#32ADE6',
    },
    gastronomia: {
        order: 3,
        name: 'Gastronomía',
        slug: 'gastronomia',
        markerUrl: '/gastronomia-marker.svg',
        iconUrl: '/gastronomia-icon.svg',
        color: '#34C759',
    },
    negocios: {
        order: 8,
        name: 'Negocios',
        slug: 'negocios',
        markerUrl: '/negocios-marker.svg',
        iconUrl: '/negocios-icon.svg',
        color: '#1C3983',
    },
}
